### ISSUE TITLE
Cant Start Up Bounds (fixed)

### ISSUE THREAD

**Issue by GuacamoleJones** [ChosenArchitect/Bounds-1.12-Modpack#145]
So I downloaded this pack and this keeps happening, just to let you know I have optifine and SUES shaders. This is the error message ---- Minecraft Crash Report ----

WARNING: coremods are present:
  RBLoadingPlugin (RealBench-1.12.2-1.3.3 (1).jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5 (1).jar)
  BedPatch (bedpatch-2.2-1.12.2 (1).jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4 (1).jar)
  BCModPlugin (backpacks 1.12.2 - 3.5.2 (1).jar)
  FarseekCoreMod (Farseek-1.12-2.3.1 (1).jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10 (1).jar)
  FMLPlugin (elulib-0.1.12 (1).jar)
  LoadingPlugin (BetterWithLib-1.3 (1).jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.10.1-1.12.2 (1).jar)
  BlurPlugin (Blur-1.0.4-14 (1).jar)
  LoadingPlugin (Quark-r1.5-129 (1).jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.1.0 (1).jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3 (1).jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18 (1).jar)
  IvToolkit (IvToolkit-1.3.3-1.12 (1).jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.16 (1).jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63 (1).jar)
  LoadingPlugin (HardcoreBuoy-1.12-1.0.4 (1).jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 3/28/19 7:12 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CTM (ctm)
Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 116
Exception Details:
  Location:
    net/minecraftforge/client/model/ModelLoader$VanillaModelWrapper.getTextures()Ljava/util/Collection; @116: invokestatic
  Reason:
    Type 'net/minecraftforge/client/model/IModel' (current frame, locals[1]) is not assignable to 'net/minecraft/util/ResourceLocation' (stack map, locals[1])
  Current Frame:
    bci: @14
    flags: { }
    locals: { 'net/minecraftforge/client/model/ModelLoader$VanillaModelWrapper', 'net/minecraftforge/client/model/IModel' }
    stack: { 'net/minecraftforge/client/model/IModel' }
  Stackmap Frame:
    bci: @116
    flags: { }
    locals: { 'net/minecraftforge/client/model/ModelLoader$VanillaModelWrapper', 'net/minecraft/util/ResourceLocation' }
    stack: { }
  Bytecode:
    0x0000000: 2ab4 0044 b600 9b4c 2bb8 00b5 4c2b c600
    0x0000010: 662a b400 44b4 00b8 c700 5c2b b600 9e12
    0x0000020: bab6 00bb 9900 102a b400 44b8 00bf b500
    0x0000030: b8a7 0043 2ab4 0044 2bbb 0080 59b7 0081
    0x0000040: 12c1 b600 872b b600 8a12 c3b6 0087 2ab4
    0x0000050: 0044 b600 8a12 c5b6 0087 b600 8db8 0093
    0x0000060: b900 c901 002a ba00 db00 00b6 00e1 c000
    0x0000070: 54b5 00b8 b800 e54d 2ab4 003d 2ab4 0044
    0x0000080: b800 e999 004a b200 efb9 00f2 0100 4e2d
    0x0000090: b900 6501 0099 0038 2db9 0069 0100 c000
    0x00000a0: a23a 042a b400 4419 04b6 00f6 3a05 bb00
    0x00000b0: 6b59 1905 b700 f93a 0619 0519 04b6 00bb
    0x00000c0: 9a00 0a2c 1906 b600 fc57 a7ff c52a b400
    0x00000d0: 44b4 0100 b901 0301 00b9 005d 0100 4e2d
    0x00000e0: b900 6501 0099 002a 2db9 0069 0100 c000
    0x00000f0: a23a 0419 0413 0105 b600 a69a 0011 2cbb
    0x0000100: 006b 5919 04b7 00f9 b600 fc57 a7ff d32c
    0x0000110: b601 09b0                              
  Stackmap Table:
    append_frame(@52,Object[#107])
    same_frame(@116)
    append_frame(@143,Object[#14],Object[#97])
    same_frame(@202)
    chop_frame(@205,1)
    append_frame(@223,Object[#97])
    same_frame(@268)
    chop_frame(@271,1)

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at team.chisel.ctm.client.util.TextureMetadataHandler.<clinit>(TextureMetadataHandler.java:102)
	at team.chisel.ctm.CTM.preInit(CTM.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 262689248 bytes (250 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2814 Optifine OptiFine_1.12.2_HD_U_E3 145 mods loaded, 145 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' =
If anyone can fix it I would be very happy!

**Comment by GuacamoleJones** [comment]
Don't worry guys, I was able to fix it!

**Comment by Habeeb-M** [comment]
How did you fix it? @GuacamoleJones

**Comment by YavuzGGWP** [comment]
I am curious too!

**Comment by Habeeb-M** [comment]
Found it! https://github.com/Chisel-Team/Chisel/issues/751

Update Chisel/CTM
