### ISSUE TITLE
Game Crash 

### ISSUE THREAD

**Issue by DarkRaGaming** [ChosenArchitect/Bounds-1.12-Modpack#146]
The game crashed whilst initializing game
Error: org.lwjgl.LWJGLException: Pixel format not accelerated

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FarseekCoreMod (Farseek-1.12-2.3.1.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  BCModPlugin (backpacks 1.12.2 - 3.5.2.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  LoadingPlugin (HardcoreBuoy-1.12-1.0.4.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  LoadingPlugin (Quark-r1.5-129.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  FMLPlugin (elulib-0.1.12.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  LoadingPlugin (BetterWithLib-1.3.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.1.0.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.16.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.10.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 4/17/19 12:04 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:644)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:457)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:644)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:457)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 612942664 bytes (584 MB) / 1023934464 bytes (976 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
FarseekCoreMod (Farseek-1.12-2.3.1.jar)
  farseek.core.FarseekClassTransformer
RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
BCModPlugin (backpacks 1.12.2 - 3.5.2.jar)
  brad16840.core.ClassTransformer
BedPatch (bedpatch-2.2-1.12.2.jar)
  com.mordenkainen.bedpatch.BedPatchASM
LoadingPlugin (HardcoreBuoy-1.12-1.0.4.jar)
  betterwithmods.core.ClassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
LoadingPlugin (Quark-r1.5-129.jar)
  vazkii.quark.base.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (BetterWithLib-1.3.jar)
  betterwithmods.bwl.core.ClassTransformer
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
ColytraLoadingPlugin (colytra-1.12.2-1.1.0.jar)
  c4.colytra.asm.ElytraTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.16.jar)
  org.blockartistry.DynSurround.asm.Transformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.10.1-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	Launched Version: forge-14.23.4.2760
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>

**Comment by Habeeb-M** [comment]
This can be easily fixed by updating your graphics drivers.
