### ISSUE TITLE
NEX crashing

### ISSUE THREAD

**Issue by lhdev** [ChosenArchitect/Bounds-1.12-Modpack#30]
We are experiencing issues on the server where NEX is causing crashes while just exploring or digging through netherrack.  The crash log shows the following:

```
java.lang.NullPointerException: Exception ticking world
        at nex.world.gen.ChunkGeneratorNether.func_185931_b(ChunkGeneratorNether.java:411)
        at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
        at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:988)
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
        at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
        at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by lhdev** [comment]
Just for testing, I copied the Sevtech NetherEx config folder and regen'd the nether on my server.  It seems to be working without issues.  I only did that because it's a tried and true pack that included NetherEx.

I'm guessing something with the configs needs to be changed.
