### ISSUE TITLE
Update forge config

### ISSUE THREAD

**Issue by lhdev** [ChosenArchitect/Bounds-1.12-Modpack#46]
Need to update the forge config to remove ticking entities so the server doesn't crash.  Had an issue tonight.  Was able to fix it by changing the forge.cfg file to remove ticking entities.

```
Stacktrace:
	at net.minecraftforge.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:159)
	at de.lellson.roughmobs2.ai.misc.RoughAIDespawn.func_75246_d(RoughAIDespawn.java:50)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.passive.AbstractHorse.func_70636_d(AbstractHorse.java:635)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.passive.AbstractHorse.func_70071_h_(AbstractHorse.java:682)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: minecraft:zombie_horse (net.minecraft.entity.passive.EntityZombieHorse)
	Entity ID: 138
	Entity Name: Zombie Horse
	Entity's Exact location: 356.50, 68.00, -90.50
	Entity's Block location: World: (356,68,-91), Chunk: (at 4,4,5 in 22,-6; contains blocks 352,0,-96 to 367,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [EntityZombie['Zombie'/139, l='world', x=356.50, y=68.00, z=-90.50]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
```

**Comment by jellonek** [comment]
Similar thing in single player mode (zombie horse in nether fortress):
```
[15:46:41] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: java.lang.IllegalArgumentException: Can not set boolean field net.minecraft.entity.EntityLivingBase.field_70729_aU to java.lang.Integer
	at net.minecraftforge.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:159) ~[forge-1.12.2-14.23.4.2747-universal.jar:?]
	at de.lellson.roughmobs2.ai.misc.RoughAIDespawn.func_75246_d(RoughAIDespawn.java:50) ~[RoughAIDespawn.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) ~[xf.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) ~[vq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) ~[vq.class:?]
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178) ~[vd.class:?]
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43) ~[zv.class:?]
	at net.minecraft.entity.passive.AbstractHorse.func_70636_d(AbstractHorse.java:635) ~[aao.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[vq.class:?]
	at net.minecraft.entity.passive.AbstractHorse.func_70071_h_(AbstractHorse.java:682) ~[aao.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1990) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1952) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1756) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
Caused by: java.lang.IllegalArgumentException: Can not set boolean field net.minecraft.entity.EntityLivingBase.field_70729_aU to java.lang.Integer
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source) ~[?:1.8.0_171]
	at sun.reflect.UnsafeBooleanFieldAccessorImpl.set(Unknown Source) ~[?:1.8.0_171]
	at java.lang.reflect.Field.set(Unknown Source) ~[?:1.8.0_171]
	at net.minecraftforge.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:155) ~[forge-1.12.2-14.23.4.2747-universal.jar:?]
	at de.lellson.roughmobs2.ai.misc.RoughAIDespawn.func_75246_d(RoughAIDespawn.java:50) ~[RoughAIDespawn.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) ~[xf.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) ~[vq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) ~[vq.class:?]
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178) ~[vd.class:?]
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43) ~[zv.class:?]
	at net.minecraft.entity.passive.AbstractHorse.func_70636_d(AbstractHorse.java:635) ~[aao.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[vq.class:?]
	at net.minecraft.entity.passive.AbstractHorse.func_70071_h_(AbstractHorse.java:682) ~[aao.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1990) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1952) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1756) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more```

Addional data:
```
// Uh... Did I do that?

Time: 8/3/18 3:46 PM
Description: Ticking entity

net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: java.lang.IllegalArgumentException: Can not set boolean field net.minecraft.entity.EntityLivingBase.field_70729_aU to java.lang.Integer
	at net.minecraftforge.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:159)
	at de.lellson.roughmobs2.ai.misc.RoughAIDespawn.func_75246_d(RoughAIDespawn.java:50)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.passive.AbstractHorse.func_70636_d(AbstractHorse.java:635)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.passive.AbstractHorse.func_70071_h_(AbstractHorse.java:682)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Can not set boolean field net.minecraft.entity.EntityLivingBase.field_70729_aU to java.lang.Integer
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
	at sun.reflect.UnsafeBooleanFieldAccessorImpl.set(Unknown Source)
	at java.lang.reflect.Field.set(Unknown Source)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:155)
	... 21 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.relauncher.ReflectionHelper.setPrivateValue(ReflectionHelper.java:159)
	at de.lellson.roughmobs2.ai.misc.RoughAIDespawn.func_75246_d(RoughAIDespawn.java:50)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43)
	at net.minecraft.entity.passive.AbstractHorse.func_70636_d(AbstractHorse.java:635)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.passive.AbstractHorse.func_70071_h_(AbstractHorse.java:682)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: minecraft:zombie_horse (net.minecraft.entity.passive.EntityZombieHorse)
	Entity ID: 429815
	Entity Name: Zombie Horse
	Entity's Exact location: -55.50, 73.00, -71.50
	Entity's Block location: World: (-56,73,-72), Chunk: (at 8,4,8 in -4,-5; contains blocks -64,0,-80 to -49,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: 2
	All players: 1 total; [EntityPlayerMP['jell_pl'/396395, l='2', x=-55.03, y=73.00, z=-39.62]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -3945516488851004082
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by lhdev** [comment]
I think Zombie Horses just need to be removed from the rough mobs config then.
